---
- hosts: web_servers
  become: yes

  tasks:
    - name: install epel
      yum: name=epel-release update_cache=yes state=latest
    - name: install apache2
      yum: name=httpd update_cache=yes state=latest
    - name: start apache
      service: name=httpd state:started
    - name: copy index template
      template: src=templates/index.html.j2 dest=/var/www/html/index.html 



